import { useState, useCallback, useRef, useEffect } from "react";
import { useSimpleSpeechRecognition } from "./useSimpleSpeechRecognition";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

type AssistantState = 'idle' | 'listening' | 'processing';

export const useVoiceAssistant = (currentRoute: string) => {
  const [state, setState] = useState<AssistantState>('idle');
  const [lastQuery, setLastQuery] = useState("");
  const [lastResponse, setLastResponse] = useState("");
  const transcriptRef = useRef("");
  const routeRef = useRef(currentRoute);
  
  // No longer using TTS hook - audio is handled separately per message
  const recognition = useSimpleSpeechRecognition();

  // Keep refs updated
  useEffect(() => {
    routeRef.current = currentRoute;
  }, [currentRoute]);

  useEffect(() => {
    if (recognition.transcript) {
      transcriptRef.current = recognition.transcript;
    }
  }, [recognition.transcript]);

  // Show errors as toasts
  useEffect(() => {
    if (recognition.error) {
      toast.error(recognition.error);
    }
  }, [recognition.error]);

  const processQuery = useCallback(async (query: string) => {
    if (!query.trim()) {
      setState('idle');
      return;
    }

    setState('processing');
    setLastQuery(query);
    setLastResponse(""); // Clear previous response

    const startTime = performance.now();
    console.log('[VoiceAssistant] Processing query:', query.substring(0, 50) + '...');

    try {
      // Get current session for authenticated request
      const { data: { session } } = await supabase.auth.getSession();
      const token = session?.access_token || SUPABASE_ANON_KEY;

      const isMatiaSession = !session && localStorage.getItem('erbi:matia_session') === 'true';
      const headers: Record<string, string> = {
        'Content-Type': 'application/json',
        'apikey': SUPABASE_ANON_KEY,
        'Authorization': `Bearer ${token}`,
      };
      if (isMatiaSession) {
        headers['X-Matia-Session'] = 'true';
      }

      const response = await fetch(
        `${SUPABASE_URL}/functions/v1/voice-assistant`,
        {
          method: 'POST',
          headers,
          body: JSON.stringify({ query, route: routeRef.current }),
        }
      );

      const endTime = performance.now();
      console.log(`[VoiceAssistant] Response received in ${Math.round(endTime - startTime)}ms`);

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        if (response.status === 401 || response.status === 403) {
          toast.error(errorData.error || 'Se requiere rol de administrador');
        } else {
          toast.error('Error al procesar la consulta');
        }
        setState('idle');
        return;
      }

      const data = await response.json();
      const responseText = data.response || 'No pude obtener una respuesta.';
      
      setLastResponse(responseText);
      setState('idle');
      
      console.log('[VoiceAssistant] Response text ready, audio will be generated by MessageAudioButton');
      
    } catch (error) {
      console.error('[VoiceAssistant] Error:', error);
      toast.error('Error al procesar tu pregunta');
      setState('idle');
    }
  }, []);

  const startVoice = useCallback(async () => {
    if (!recognition.isSupported) {
      toast.error('Tu navegador no soporta reconocimiento de voz');
      return;
    }

    // If already listening, stop and process
    if (state === 'listening' || recognition.isListening) {
      const finalTranscript = recognition.stopListening();
      const queryText = finalTranscript || transcriptRef.current;

      if (queryText.trim()) {
        processQuery(queryText.trim());
      } else {
        toast.info('No escuché nada. Intenta hablar más cerca del micrófono.');
        setState('idle');
      }
      return;
    }

    // Start listening - permission is requested inside startListening
    setState('listening');
    transcriptRef.current = "";
    recognition.resetTranscript();
    await recognition.startListening();
  }, [processQuery, recognition, state]);

  const sendTextQuery = useCallback((text: string) => {
    processQuery(text);
  }, [processQuery]);

  const stopAll = useCallback(() => {
    if (recognition.isListening) recognition.stopListening();
    setState('idle');
  }, [recognition]);

  const clearConversation = useCallback(() => {
    setLastQuery("");
    setLastResponse("");
  }, []);

  return {
    state,
    isListening: state === 'listening' || recognition.isListening,
    isProcessing: state === 'processing',
    transcript: recognition.transcript,
    error: recognition.error,
    lastQuery,
    lastResponse,
    isSupported: recognition.isSupported,
    startVoice,
    sendTextQuery,
    stopAll,
    clearConversation,
    // Expose recognition methods for direct use
    startListening: recognition.startListening,
    stopListening: recognition.stopListening,
    resetTranscript: recognition.resetTranscript,
  };
};
